# Generated by Django 4.2.13 on 2024-06-08 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createevent',
            name='event_created_date',
            field=models.DateField(null=True),
        ),
    ]
