# Generated by Django 4.2.13 on 2024-06-08 17:07

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationInstruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instruct', ckeditor.fields.RichTextField()),
            ],
            options={
                'verbose_name_plural': 'Donation Instruction',
                'db_table': 'Donation Instruction',
            },
        ),
        migrations.CreateModel(
            name='FeedbackInstruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instruct', ckeditor.fields.RichTextField()),
            ],
            options={
                'verbose_name_plural': 'Feedback Instruction',
                'db_table': 'Feedback Instruction',
            },
        ),
        migrations.CreateModel(
            name='MemberInstruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instruct', ckeditor.fields.RichTextField()),
            ],
            options={
                'verbose_name_plural': 'Member Instruction',
                'db_table': 'Member Instruction',
            },
        ),
        migrations.CreateModel(
            name='VacancyInstruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instruct', ckeditor.fields.RichTextField()),
            ],
            options={
                'verbose_name_plural': 'Vacancy Instruction',
                'db_table': 'Vacancy Instruction',
            },
        ),
        migrations.AlterModelOptions(
            name='feedback',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Feedback'},
        ),
        migrations.AlterField(
            model_name='donation',
            name='postal_code',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='member',
            name='postal_code',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterModelTable(
            name='feedback',
            table='Feedback',
        ),
    ]
