# Generated by Django 4.2.13 on 2024-05-25 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adversite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/advertise/')),
            ],
            options={
                'verbose_name_plural': 'Advertisement',
                'db_table': 'Advertisement',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='President',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='images/president/')),
                ('p_message', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'President',
                'db_table': 'President',
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='images/slider/')),
                ('title', models.CharField(max_length=100)),
                ('sub_title', models.CharField(max_length=254)),
            ],
            options={
                'verbose_name_plural': 'Slider',
                'db_table': 'Slider',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name_plural': 'Subscribe',
                'db_table': 'Subscribe',
                'ordering': ['-id'],
            },
        ),
    ]
