# Generated by Django 4.2.13 on 2024-06-08 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Advertise',
            new_name='Advertisement',
        ),
    ]
