# Generated by Django 4.2.13 on 2024-05-25 18:52

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_content', ckeditor.fields.RichTextField()),
            ],
            options={
                'verbose_name_plural': 'About SNS',
                'db_table': 'About SNS',
            },
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term_content', ckeditor.fields.RichTextField()),
            ],
            options={
                'verbose_name_plural': 'Terms and Condition',
                'db_table': 'Terms and Condition',
            },
        ),
        migrations.CreateModel(
            name='Vision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vision_content', ckeditor.fields.RichTextField()),
            ],
            options={
                'verbose_name_plural': 'Vision',
                'db_table': 'Vision',
            },
        ),
    ]
