# Generated by Django 4.2.13 on 2024-05-25 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appreciations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=254)),
                ('c_date', models.DateField()),
                ('files', models.FileField(max_length=254, upload_to='files/appreciations/')),
            ],
            options={
                'verbose_name_plural': 'Appreciation',
                'db_table': 'Appreciation',
            },
        ),
        migrations.CreateModel(
            name='Laws',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=254)),
                ('c_date', models.DateField()),
                ('files', models.FileField(max_length=254, upload_to='files/laws/')),
            ],
            options={
                'verbose_name_plural': 'Laws and Convention',
                'db_table': 'Laws and Convention',
            },
        ),
        migrations.CreateModel(
            name='Program_Registrations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('participant_full_name', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=400)),
                ('province', models.CharField(max_length=400)),
                ('postal_code', models.IntegerField(blank=True, null=True)),
                ('your_contact', models.CharField(help_text='your contact number', max_length=15)),
                ('your_email', models.EmailField(max_length=254)),
                ('parents_full_name', models.CharField(max_length=200)),
                ('parents_contact', models.CharField(help_text='your contact number', max_length=15)),
                ('parents_email', models.EmailField(max_length=254)),
                ('program', models.CharField(choices=[('S', 'summer'), ('W', 'winter')], max_length=1)),
                ('screenshot', models.ImageField(upload_to='images/payments/program_registration/')),
                ('status', models.CharField(choices=[('C', 'Confirmed'), ('U', 'Unconfirm')], default='U', max_length=1)),
            ],
            options={
                'verbose_name_plural': 'Program Registration',
                'db_table': 'Program Registration',
            },
        ),
        migrations.CreateModel(
            name='References',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=254)),
                ('c_date', models.DateField()),
                ('files', models.FileField(max_length=254, upload_to='files/references/')),
            ],
            options={
                'verbose_name_plural': 'Reference',
                'db_table': 'Reference',
            },
        ),
        migrations.CreateModel(
            name='Registrations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=254)),
                ('c_date', models.DateField()),
                ('files', models.FileField(max_length=254, upload_to='files/registrations/')),
            ],
            options={
                'verbose_name_plural': 'Registration',
                'db_table': 'Registration',
            },
        ),
    ]
