# Generated by Django 4.2.13 on 2024-06-08 17:15

import ckeditor.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('document_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationInstruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instruct', ckeditor.fields.RichTextField()),
            ],
            options={
                'verbose_name_plural': 'Registration Instruction',
                'db_table': 'Registration Instruction',
            },
        ),
        migrations.AddField(
            model_name='program_registrations',
            name='manual',
            field=models.FileField(default=django.utils.timezone.now, upload_to='files/registrations/manual/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='program_registrations',
            name='parents_contact',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='program_registrations',
            name='postal_code',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='program_registrations',
            name='program',
            field=models.CharField(choices=[('SUMMER', 'summer'), ('WINTER', 'winter')], max_length=12),
        ),
        migrations.AlterField(
            model_name='program_registrations',
            name='your_contact',
            field=models.CharField(max_length=15),
        ),
    ]
